name: Build and Push Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push image with unique tag and latest
      run: |
        docker build -t tomasbeltran/frontend:${SHORT_SHA} -t tomasbeltran/frontend:latest .
        docker push tomasbeltran/frontend:${SHORT_SHA}
        docker push tomasbeltran/frontend:latest

    - name: Show pushed tag
      run: |
        echo "Pushed image: tomasbeltran/frontend:${SHORT_SHA}"

    - name: Checkout manifests repo
      uses: actions/checkout@v3
      with:
        repository: EGICloud/gitops
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: manifests

    - name: Replace image tag in deployment.yaml
      run: |
        sed -i "s|image: tomasbeltran/frontend:.*|image: tomasbeltran/frontend:${SHORT_SHA}|g" manifests/micro-frontend/base/deployment.yaml

    - name: Commit and push deployment.yaml
      working-directory: manifests
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add micro-frontend/base/deployment.yaml
        git commit -m "Update frontend image tag to ${SHORT_SHA}" || echo "No changes to commit"
        git push
