name: Build and Push Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push image with unique tag and latest
      run: |
        docker build -t tomasbeltran/frontend:${SHORT_SHA} -t tomasbeltran/frontend:latest .
        docker push tomasbeltran/frontend:${SHORT_SHA}
        docker push tomasbeltran/frontend:latest

    - name: Show pushed tag
      run: |
        echo "Pushed image: tomasbeltran/frontend:${SHORT_SHA}"

    - name: Replace image tag in deployment.yaml
      run: |
        sed -i "s|image: tomasbeltran/frontend:.*|image: tomasbeltran/frontend:${SHORT_SHA}|g" deployment.yaml

    - name: Commit and push deployment.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add deployment.yaml
        git commit -m "Update frontend image tag to ${SHORT_SHA}" || echo "No changes to commit"
        git push
